sudo: required
services:
  - docker

  before_install:
    - docker build -t adithyasekar/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true adithyasekar/docker-react npm run test -- --coverage
