name: Deployment From Github To AWS
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:16-alpine
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Build the dev docker files
        run: docker build -t adithyasekar/docker-react -f Dockerfile.dev .

      - name: Run the tests
        run: docker run -e CI=true adithyasekar/docker-react npm run test -- --coverage
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: "dashboard-react-athoc-deployment-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
